stages:
  - test
  - build
  - deploy-website

test:
  image: node:lts
  stage: test
  before_script:
    - yarn
    - yarn run lerna bootstrap
  script:
    - yarn test --verbose


build packages:
  image: node:lts
  stage: build
  before_script:
    - yarn
    - yarn run lerna bootstrap
  script:
    - yarn build

build docs:
  image: node:lts
  stage: build
  before_script:
    - yarn
    - yarn run lerna bootstrap
    - yarn build
  script:
    - cd website
    - yarn docusaurus parse
    - yarn docusaurus glossary
    - STAGING=true yarn build

pages:
  image: node:lts
  stage: deploy-website
  only:
    - master
  when: manual
  before_script:
    - yarn
    - yarn run lerna bootstrap
    - yarn build
  script:
    - cd website
    - yarn docusaurus parse
    - yarn docusaurus glossary
    - STAGING=true yarn build
    - mv build ../public
  artifacts:
    paths:
      - public
